# Generated by Django 6.0.4 on 2026-04-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В процессе'), ('done', 'Сделано'), ('archived', 'В архиве')], default='todo', max_length=20),
        ),
    ]
