# Generated by Django 6.0.4 on 2026-04-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
