# Generated by Codex on 2026-05-01

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_telegramaccount_telegramlinktoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('donor_name', models.CharField(blank=True, max_length=120)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('any', 'Все доступные способы'), ('bank_card', 'Банковская карта'), ('sbp', 'СБП'), ('yoo_money', 'ЮMoney')], default='any', max_length=24)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Отменен')], default='created', max_length=20)),
                ('provider', models.CharField(default='yookassa', max_length=32)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_url', models.URLField(blank=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='todo_don_status_created_idx'),
                    models.Index(fields=['provider_payment_id'], name='todo_don_payment_id_idx'),
                    models.Index(fields=['public_id'], name='todo_don_public_id_idx'),
                ],
            },
        ),
    ]
